/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Custom NEURAL_OS theme colors from design reference
        "on-secondary-fixed-variant": "#6900b3",
        "on-error": "#690005",
        "on-secondary-fixed": "#2c0051",
        "secondary-fixed-dim": "#ddb7ff",
        "primary-fixed": "#c4e8fc",
        "on-surface": "#e5e2e1",
        "surface-bright": "#3a3939",
        "surface-container": "#201f1f",
        "on-background": "#e5e2e1",
        "on-secondary": "#490080",
        "tertiary-fixed": "#9cf0ff",
        "on-primary-fixed": "#001e2b",
        "outline-variant": "#42484b",
        "secondary": "#ddb7ff",
        "on-tertiary-fixed-variant": "#004f58",
        "surface-dim": "#131313",
        "primary-container": "#bbdef2",
        "secondary-container": "#6f00be",
        "primary": "#ecf7ff",
        "surface-container-low": "#1c1b1b",
        "inverse-primary": "#416374",
        "secondary-fixed": "#f0dbff",
        "on-tertiary-container": "#006875",
        "on-primary-fixed-variant": "#294b5b",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-fixed": "#001f24",
        "on-error-container": "#ffdad6",
        "tertiary": "#e1faff",
        "surface": "#131313",
        "tertiary-fixed-dim": "#00daf3",
        "background": "#131313",
        "on-secondary-container": "#d6a9ff",
        "on-primary-container": "#416374",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-tint": "#a9cbdf",
        "surface-container-lowest": "#0e0e0e",
        "on-primary": "#0f3444",
        "on-tertiary": "#00363d",
        "error": "#ffb4ab",
        "tertiary-container": "#6beaff",
        "on-surface-variant": "#c2c7cc",
        "inverse-on-surface": "#313030",
        "primary-fixed-dim": "#a9cbdf",
        "error-container": "#93000a",
        "outline": "#8c9196",
        "surface-variant": "#353534"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(to right, #ecf7ff, #ddb7ff, #e1faff)',
      },
      animation: {
        'spin-slow': 'spin-slow 12s linear infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
      },
      keyframes: {
        'spin-slow': {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: '0.4', transform: 'scale(1)' },
          '50%': { opacity: '0.7', transform: 'scale(1.05)' },
        },
      },
    },
  },
  plugins: [],
}
